#ASSIGNMENT=wp1p1
#ASSIGNMENT=wp1
#ASSIGNMENT=wp2
#ASSIGNMENT=wp3
ASSIGNMENT=project
TEAM_MEMBERS_CSV="bgoyal(111482386), Aman Agarwal (amaagarwal)"
# list space-separated completed components: cooperative
PROJECT_PARTS=cooperative signals
PROJECT_POINTS=50
